language: python
sudo: true
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y chromium
install: pip install -r requirements.txt
script: 
  -python superlists/manage.py test
  -python functional_tests.py
